env:
  browser: true
  es2021: true
  node: true
extends:
  - 'plugin:react/recommended'
  - airbnb
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 12
  sourceType: module
plugins:
  - react
  - '@typescript-eslint'
settings:
  import/resolver:
    node:
      extensions: [ '.js', '.jsx', '.ts', '.tsx', '.json' ]
rules:
  no-unused-vars: 0
  no-shadow: 0
  '@typescript-eslint/no-unused-vars': [ "error" ]
  '@typescript-eslint/no-shadow': [ "error" ]
  import/extensions:
    - error
    - ignorePackages
    - js: never
      jsx: never
      ts: never
      tsx: never
