env:
  browser: true
  es2021: true
  node: true
extends:
  - airbnb
  - airbnb/hooks
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 12
  sourceType: module
plugins:
  - react
  - '@typescript-eslint'
settings:
  import/resolver:
    node:
      extensions: [ '.js', '.jsx', '.ts', '.tsx', '.json' ]
rules:
  "no-use-before-define": "off"
  "no-param-reassign": ["error", { "props": false }]
  react/prop-types: 0
  no-unused-vars: 0
  no-shadow: 0
  no-console: 0
  '@typescript-eslint/no-unused-vars': [ "error" ]
  '@typescript-eslint/no-shadow': [ "error" ]
  react/jsx-props-no-spreading: 0
  import/extensions:
    - error
    - ignorePackages
    - js: never
      jsx: never
      ts: never
      tsx: never
